apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: reverseproxy
  name: reverseproxy
  namespace: vote
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reverseproxy
  template:
    metadata:
      labels:
        app: reverseproxy
    spec:
      containers:
      - image: amrayn/dogcat-reverseproxy:1.1
        name: reverseproxy
        ports:
        - containerPort: 80
          name: reverseproxy
